"""Bible Engine Core Library (Zero External Dependencies)."""

from core.crypto import (
    MAGIC_HEADER,
    ChaCha20,
    CryptoError,
    decrypt_bytes,
    decrypt_string,
    decrypt_text_pack,
    derive_key,
    encrypt_bytes,
    encrypt_string,
    encrypt_text_pack,
    generate_key,
    keystream_xor,
)
from core.db import (
    DEFAULT_DB_PATH,
    CrossReferenceRecord,
    Database,
    SearchResult,
    SpanRecord,
    TagRecord,
    TranslationRecord,
    VerseRecord,
    VerseTagRecord,
    sanitize_fts_query,
)
from core.reference import (
    ALL_BOOKS,
    BOOKS,
    Book,
    Reference,
    canonical_id_to_triple,
    get_book,
    parse_reference,
    parse_references,
    verse_canonical_id,
)

from core.bootstrap import (
    BootstrapReport,
    bootstrap_database,
    get_db_stats,
)
from core.crossref import (
    CANONICAL_CROSS_REFERENCES,
    CrossReferenceGraphNode,
    CrossReferenceService,
    CrossReferenceSummary,
    HydratedCrossReference,
    RelationshipType,
)
from core.tags import (
    BookTopicDensity,
    CANONICAL_TAXONOMY,
    TagCategory,
    TagCoOccurrence,
    TagCoOccurrenceMatrix,
    TagSummary,
    TaggedPassage,
    TaggingService,
    VerseRelevance,
)
from core.tag_prompts import (
    GeneratedTag,
    TaggingResult,
    format_prompt_for_gemini_api,
    format_taxonomy_for_prompt,
    generate_batch_tagging_prompts,
    generate_tagging_prompt,
    get_tgc_hermeneutical_system_prompt,
    parse_tagging_response,
)
from core.terminal import (
    BOLD_GOLD,
    CANONICAL_DIVISIONS,
    THEMES,
    format_aligned_comparison_styled,
    format_citation_header,
    format_cross_reference_table,
    format_cross_references,
    format_redemptive_ribbon_ascii,
    format_scripture_passage,
    format_tag_table,
    format_tagged_passages,
    format_tags_badge,
    format_topic_density_table,
    format_tag_co_occurrence_table,
    format_verse_relevance_table,
    get_terminal_width,
    should_use_color,
    strip_ansi,
    visual_len,
)

__all__ = [
    # Reference
    "Book",
    "Reference",
    "get_book",
    "parse_reference",
    "parse_references",
    "verse_canonical_id",
    "canonical_id_to_triple",
    "BOOKS",
    "ALL_BOOKS",
    # Database
    "Database",
    "DEFAULT_DB_PATH",
    "VerseRecord",
    "TranslationRecord",
    "SpanRecord",
    "TagRecord",
    "VerseTagRecord",
    "CrossReferenceRecord",
    "SearchResult",
    "sanitize_fts_query",
    # Semantic Tagging
    "TagCategory",
    "TagSummary",
    "TaggedPassage",
    "TaggingService",
    "CANONICAL_TAXONOMY",
    "BookTopicDensity",
    "TagCoOccurrence",
    "TagCoOccurrenceMatrix",
    "VerseRelevance",
    "GeneratedTag",
    "TaggingResult",
    "get_tgc_hermeneutical_system_prompt",
    "format_taxonomy_for_prompt",
    "generate_tagging_prompt",
    "generate_batch_tagging_prompts",
    "parse_tagging_response",
    "format_prompt_for_gemini_api",
    # Cross References
    "RelationshipType",
    "CrossReferenceService",
    "HydratedCrossReference",
    "CrossReferenceSummary",
    "CANONICAL_CROSS_REFERENCES",
    # Crypto
    "ChaCha20",
    "CryptoError",
    "MAGIC_HEADER",
    "generate_key",
    "derive_key",
    "keystream_xor",
    "encrypt_bytes",
    "decrypt_bytes",
    "encrypt_string",
    "decrypt_string",
    "encrypt_text_pack",
    "decrypt_text_pack",
    # Terminal & Typography
    "THEMES",
    "BOLD_GOLD",
    "should_use_color",
    "get_terminal_width",
    "strip_ansi",
    "visual_len",
    "format_citation_header",
    "format_scripture_passage",
    "format_aligned_comparison_styled",
    "format_tags_badge",
    "format_tag_table",
    "format_tagged_passages",
    "format_topic_density_table",
    "format_tag_co_occurrence_table",
    "format_verse_relevance_table",
    "format_redemptive_ribbon_ascii",
    "CANONICAL_DIVISIONS",
    "format_cross_references",
    "format_cross_reference_table",
    # Bootstrap & Lifecycle
    "BootstrapReport",
    "bootstrap_database",
    "get_db_stats",
]

