"""Bible Engine Core Library (Zero External Dependencies)."""

from core.crypto import (
    MAGIC_HEADER,
    ChaCha20,
    CryptoError,
    decrypt_bytes,
    decrypt_string,
    decrypt_text_pack,
    derive_key,
    encrypt_bytes,
    encrypt_string,
    encrypt_text_pack,
    generate_key,
    keystream_xor,
)
from core.db import (
    DEFAULT_DB_PATH,
    CrossReferenceRecord,
    Database,
    SearchResult,
    SpanRecord,
    TagRecord,
    TranslationRecord,
    VerseRecord,
    VerseTagRecord,
    sanitize_fts_query,
)
from core.reference import (
    ALL_BOOKS,
    BOOKS,
    Book,
    Reference,
    canonical_id_to_triple,
    get_book,
    parse_reference,
    parse_references,
    verse_canonical_id,
)

from core.crossref import (
    CANONICAL_CROSS_REFERENCES,
    CrossReferenceGraphNode,
    CrossReferenceService,
    CrossReferenceSummary,
    HydratedCrossReference,
    RelationshipType,
)
from core.tags import (
    CANONICAL_TAXONOMY,
    TagCategory,
    TagSummary,
    TaggedPassage,
    TaggingService,
)
from core.terminal import (
    BOLD_GOLD,
    THEMES,
    format_aligned_comparison_styled,
    format_citation_header,
    format_cross_reference_table,
    format_cross_references,
    format_scripture_passage,
    format_tag_table,
    format_tagged_passages,
    format_tags_badge,
    get_terminal_width,
    should_use_color,
    strip_ansi,
    visual_len,
)

__all__ = [
    # Reference
    "Book",
    "Reference",
    "get_book",
    "parse_reference",
    "parse_references",
    "verse_canonical_id",
    "canonical_id_to_triple",
    "BOOKS",
    "ALL_BOOKS",
    # Database
    "Database",
    "DEFAULT_DB_PATH",
    "VerseRecord",
    "TranslationRecord",
    "SpanRecord",
    "TagRecord",
    "VerseTagRecord",
    "CrossReferenceRecord",
    "SearchResult",
    "sanitize_fts_query",
    # Semantic Tagging
    "TagCategory",
    "TagSummary",
    "TaggedPassage",
    "TaggingService",
    "CANONICAL_TAXONOMY",
    # Cross References
    "RelationshipType",
    "CrossReferenceService",
    "HydratedCrossReference",
    "CrossReferenceSummary",
    "CANONICAL_CROSS_REFERENCES",
    # Crypto
    "ChaCha20",
    "CryptoError",
    "MAGIC_HEADER",
    "generate_key",
    "derive_key",
    "keystream_xor",
    "encrypt_bytes",
    "decrypt_bytes",
    "encrypt_string",
    "decrypt_string",
    "encrypt_text_pack",
    "decrypt_text_pack",
    # Terminal & Typography
    "THEMES",
    "BOLD_GOLD",
    "should_use_color",
    "get_terminal_width",
    "strip_ansi",
    "visual_len",
    "format_citation_header",
    "format_scripture_passage",
    "format_aligned_comparison_styled",
    "format_tags_badge",
    "format_tag_table",
    "format_tagged_passages",
    "format_cross_references",
    "format_cross_reference_table",
]

